zxh:
  profile: C:/Users/Admin/Desktop/1/images
server:
  port: 8888
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
    min-response-size: 1KB
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: root
    password: return.0
    url: jdbc:mysql://8.148.238.119:3306/zxh?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/file/
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
logging:
  level:
    com.zxh: debug
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
